Revert "seq_file: remove "%n" usage from seq_file users"
This reverts commit 4a354acc1866fe2d01e148091961cfe466074b59.

../../../../../../kernel/htc/msm8960/fs/proc/task_mmu.c: In function 'show_map_vma':
../../../../../../kernel/htc/msm8960/fs/proc/task_mmu.c:289:4: error: implicit declaration of function 'seq_print_vma_name' [-Werror=implicit-function-declaration]
    seq_print_vma_name(m, vma);
    ^
cc1: some warnings being treated as errors
make[4]: *** [fs/proc/task_mmu.o] Error 1
make[3]: *** [fs/proc] Error 2
make[3]: *** Waiting for unfinished jobs....

Change-Id: Iea25170ff71380e3d7052fd08e1d1fbea3cd4e77